import type { GameLocale } from "@/lib/i18n";

type CodexNavGameLabelKey =
  | "characters"
  | "cards"
  | "keywords"
  | "relics"
  | "potions"
  | "powers"
  | "monsters"
  | "events"
  | "ancients"
  | "epochs"
  | "historyCourse";

// Exact client-safe labels from STS2 localization tables:
// main_menu_ui, gameplay_ui, static_hover_tips, epochs.
const CODEX_NAV_GAME_LABELS: Record<GameLocale, Record<CodexNavGameLabelKey, string>> = {
  deu: {
    characters: "Characters",
    cards: "Kartenbibliothek",
    keywords: "Keywords",
    relics: "Reliktsammlung",
    potions: "Tranklabor",
    powers: "Macht",
    monsters: "Bestiarium",
    events: "Ereignis",
    ancients: "Ahnen",
    epochs: "Epochen",
    historyCourse: "Geschichtskurs",
  },
  eng: {
    characters: "Characters",
    cards: "Card Library",
    keywords: "Keywords",
    relics: "Relic Collection",
    potions: "Potion Lab",
    powers: "Power",
    monsters: "Bestiary",
    events: "Event",
    ancients: "Ancients",
    epochs: "Epochs",
    historyCourse: "History Course",
  },
  esp: {
    characters: "Characters",
    cards: "Colección de cartas",
    keywords: "Keywords",
    relics: "Relicario",
    potions: "Pocionero",
    powers: "Poder",
    monsters: "Bestiario",
    events: "Evento",
    ancients: "Ancestrales",
    epochs: "Eras",
    historyCourse: "Clase de historia",
  },
  fra: {
    characters: "Characters",
    cards: "Bibliothèque",
    keywords: "Keywords",
    relics: "Reliquaire",
    potions: "Laboratoire",
    powers: "Pouvoir",
    monsters: "Bestiaire",
    events: "Événement",
    ancients: "Les Anciens",
    epochs: "Ères",
    historyCourse: "Manuel d'Histoire",
  },
  ita: {
    characters: "Characters",
    cards: "Collezione delle carte",
    keywords: "Keywords",
    relics: "Reliquiario",
    potions: "Laboratorio delle pozioni",
    powers: "Potere",
    monsters: "Bestiario",
    events: "Evento",
    ancients: "Gli Antichi",
    epochs: "Epoche",
    historyCourse: "Corso di Storia",
  },
  jpn: {
    characters: "Characters",
    cards: "カードライブラリ",
    keywords: "Keywords",
    relics: "レリック一覧",
    potions: "ポーションラボ",
    powers: "パワー",
    monsters: "モンスター図鑑",
    events: "イベント",
    ancients: "エンシェント",
    epochs: "断章",
    historyCourse: "歴史学教程",
  },
  kor: {
    characters: "캐릭터",
    cards: "카드 목록",
    keywords: "키워드",
    relics: "유물 모음집",
    potions: "포션 연구실",
    powers: "파워",
    monsters: "몬스터 도감",
    events: "이벤트",
    ancients: "고대의 존재",
    epochs: "연대기",
    historyCourse: "역사 강의서",
  },
  pol: {
    characters: "Characters",
    cards: "Kolekcja kart",
    keywords: "Keywords",
    relics: "Zbiór Artefaktów",
    potions: "Laboratorium Mikstur",
    powers: "Moc",
    monsters: "Bestiariusz",
    events: "Wydarzenie",
    ancients: "Starożytni",
    epochs: "Epoki",
    historyCourse: "Podręcznik do historii",
  },
  ptb: {
    characters: "Characters",
    cards: "Biblioteca de Cartas",
    keywords: "Keywords",
    relics: "Coleção de Relíquias",
    potions: "Laboratório de Poções",
    powers: "Poder",
    monsters: "Bestiário",
    events: "Evento",
    ancients: "Ancestrais",
    epochs: "Épocas",
    historyCourse: "Estudos de História",
  },
  rus: {
    characters: "Characters",
    cards: "Библиотека карт",
    keywords: "Keywords",
    relics: "Коллекция реликвий",
    potions: "Лаборатория",
    powers: "Талант",
    monsters: "Бестиарий",
    events: "Событие",
    ancients: "Древние",
    epochs: "Эпохи",
    historyCourse: "Лекция по истории",
  },
  spa: {
    characters: "Characters",
    cards: "Biblioteca de cartas",
    keywords: "Keywords",
    relics: "Colección de reliquias",
    potions: "Laboratorio de pociones",
    powers: "Poder",
    monsters: "Bestiario",
    events: "Evento",
    ancients: "Los Antiguos",
    epochs: "Épocas",
    historyCourse: "Libro de historia",
  },
  tha: {
    characters: "Characters",
    cards: "คลังการ์ด",
    keywords: "Keywords",
    relics: "คลังเครื่องราง",
    potions: "ห้องทดลองยา",
    powers: "พลัง",
    monsters: "คลังอสูร",
    events: "เหตุการณ์",
    ancients: "เทพโบราณ",
    epochs: "ศักราช",
    historyCourse: "หลักสูตรประวัติศาสตร์",
  },
  tur: {
    characters: "Characters",
    cards: "Kart Kütüphanesi",
    keywords: "Keywords",
    relics: "Kalıntı Koleksiyonu",
    potions: "İksir Laboratuvarı",
    powers: "Güç",
    monsters: "Yaratık Ansiklopedisi",
    events: "Etkinlik",
    ancients: "Kadimler",
    epochs: "Çağlar",
    historyCourse: "Tarih Dersi",
  },
  zhs: {
    characters: "Characters",
    cards: "卡牌总览",
    keywords: "Keywords",
    relics: "遗物收集",
    potions: "药水研究所",
    powers: "能力",
    monsters: "怪物图鉴",
    events: "事件",
    ancients: "先古之民",
    epochs: "历史节点",
    historyCourse: "历史课",
  },
};

export function getCodexNavGameLabel(
  gameLocale: GameLocale,
  key: string,
): string | undefined {
  return CODEX_NAV_GAME_LABELS[gameLocale][key as CodexNavGameLabelKey];
}
