import {
  getCodexCards,
  getCodexKeywords,
  getCodexRelics,
  getCodexPotions,
  getCodexPowers,
  getCodexEnchantments,
  getCodexAfflictions,
  getCodexEvents,
  getCodexMonsters,
  getCodexEncounters,
  getCodexAncients,
  getCodexEpochs,
} from "@/lib/codex-data";
import type { GameLocale } from "@/lib/i18n";
import type { EntityInfo } from "@/components/patch-note-renderer";
import { isPublicBestiaryMonster } from "@/lib/bestiary-monster-policy";

export async function loadAllEntities(opts?: { gameLocale?: GameLocale }): Promise<EntityInfo[]> {
  const gameLocale = opts?.gameLocale;
  const [
    codexCards,
    codexKeywords,
    codexRelics,
    codexPotions,
    codexPowers,
    codexEnchantments,
    codexAfflictions,
    codexEvents,
    codexMonsters,
    codexEncounters,
    codexAncients,
    codexEpochs,
  ] = await Promise.all([
    getCodexCards({ includeDeprecated: true, gameLocale }),
    getCodexKeywords({ gameLocale }),
    getCodexRelics({ gameLocale }),
    getCodexPotions({ gameLocale }),
    getCodexPowers({ includeDeprecated: true, gameLocale }),
    getCodexEnchantments({ gameLocale }),
    getCodexAfflictions({ gameLocale }),
    getCodexEvents({ gameLocale }),
    getCodexMonsters({ gameLocale }),
    getCodexEncounters({ gameLocale }),
    getCodexAncients({ gameLocale }),
    getCodexEpochs({ gameLocale }),
  ]);

  return [
    ...codexCards.map((c) => ({
      id: c.id,
      nameEn: c.nameEn,
      nameKo: c.name,
      imageUrl: c.imageUrl,
      color: c.color,
      type: "card" as const,
      cardData: c,
    })),
    ...codexKeywords.map((k) => ({
      id: k.id,
      nameEn: k.nameEn,
      nameKo: k.name,
      imageUrl: k.imageUrl,
      href: `/compendium/keywords/${k.id.toLowerCase()}`,
      color: k.source,
      type: "keyword" as const,
      keywordData: k,
    })),
    ...codexRelics.map((r) => ({
      id: r.id,
      nameEn: r.nameEn,
      nameKo: r.name,
      imageUrl: r.imageUrl,
      color: r.pool,
      type: "relic" as const,
      relicData: r,
    })),
    ...codexPotions.map((p) => ({
      id: p.id,
      nameEn: p.nameEn,
      nameKo: p.name,
      imageUrl: p.imageUrl,
      color: p.pool,
      type: "potion" as const,
      potionData: p,
    })),
    ...codexPowers.map((p) => ({
      id: p.id,
      nameEn: p.nameEn,
      nameKo: p.name,
      imageUrl: p.imageUrl,
      color: p.type,
      type: "power" as const,
      powerData: p,
    })),
    ...codexEnchantments.map((e) => ({
      id: e.id,
      nameEn: e.nameEn,
      nameKo: e.name,
      imageUrl: e.imageUrl,
      color: e.cardType ?? "Any",
      type: "enchantment" as const,
      enchantmentData: e,
    })),
    ...codexAfflictions.map((a) => ({
      id: a.id,
      nameEn: a.nameEn,
      nameKo: a.name,
      imageUrl: a.imageUrl,
      color: "affliction",
      type: "affliction" as const,
      afflictionData: a,
    })),
    ...codexEvents.map((e) => ({
      id: e.id,
      nameEn: e.nameEn,
      nameKo: e.name,
      imageUrl: e.imageUrl,
      color: e.act ?? "none",
      type: "event" as const,
      eventData: e,
    })),
    ...codexMonsters
      .filter((m) => m.showInCompendium && isPublicBestiaryMonster(m.id))
      .map((m) => ({
        id: m.id,
        nameEn: m.nameEn,
        nameKo: m.name,
        imageUrl: m.bossImageUrl ?? m.imageUrl,
        color: m.type,
        type: "monster" as const,
        monsterData: m,
      })),
    ...codexEncounters.map((e) => ({
      id: e.id,
      nameEn: e.nameEn,
      nameKo: e.name,
      imageUrl: e.imageUrl,
      color: e.roomType,
      type: "encounter" as const,
      encounterData: e,
    })),
    ...codexAncients.map((a) => ({
      id: a.id,
      nameEn: a.nameEn,
      nameKo: a.name,
      imageUrl: a.imageUrl,
      color: a.act ?? "none",
      type: "ancient" as const,
      ancientData: a,
    })),
    ...codexEpochs.map((e) => ({
      id: e.id,
      nameEn: e.nameEn,
      nameKo: e.name,
      imageUrl: e.imageUrl,
      href: `/compendium/epochs/${e.id.toLowerCase()}`,
      color: e.affiliation,
      type: "epoch" as const,
      epochData: e,
    })),
  ];
}
