import type { TransfigurePost } from "@/lib/transfigure-types";

// Curated built-in sample transfigure posts (featured in Byrdispatch)
export const BUILTIN_SAMPLE_TRANSFIGURES: readonly TransfigurePost[] = [
  {
    id: "ab3f946e-c6c8-4eb2-9092-e244b891b0fe",
    user_id: "system",
    nickname: "기가크릿",
    title: "허상 (메가크릿 정상화)",
    resource_type: "card",
    resource_id: "EIDOLON",
    source_text: "모든 적에게 [gold]약화[/gold]를 1 부여합니다. 턴 종료 시까지 [gold]무형[/gold]을 1 얻습니다.",
    source_game_locale: "kor",
    transformed_name: "허상",
    transformed_cost: "1",
    transformed_star_cost: null,
    transformed_card_type: "스킬",
    transformed_card_rarity: "희귀",
    transformed_card_color: "defect",
    omit_energy_cost: false,
    card_top_keywords: [],
    card_bottom_keywords: [],
    upgraded_content: null,
    upgraded_content_text: null,
    transformed_upgrade_cost: null,
    transformed_upgrade_star_cost: null,
    upgraded_card_top_keywords: [],
    upgraded_card_bottom_keywords: [],
    show_upgrade: false,
    token_color: null,
    token_wax: null,
    content: [
      {
        type: "text",
        text: "턴 종료 시까지 [gold]무형[/gold]을 1 얻습니다. [gold]소멸[/gold].",
      },
    ],
    content_text: "턴 종료 시까지 [gold]무형[/gold]을 1 얻습니다. [gold]소멸[/gold].",
    env: "production",
    created_at: "2026-07-26T00:00:00Z",
  },
  {
    id: "0b2e7754-39a4-48a3-ad0e-7abcd0030cbb",
    user_id: "system",
    nickname: "밸런스장인",
    title: "기리야 (휴식 강화)",
    resource_type: "relic",
    resource_id: "GIRYA",
    source_text: "[gold]휴식 장소[/gold]에서 최대 3번 [gold]힘[/gold]을 1 올릴 수 있습니다.",
    source_game_locale: "kor",
    transformed_name: "기리야",
    transformed_cost: null,
    transformed_star_cost: null,
    transformed_card_type: null,
    transformed_card_rarity: null,
    transformed_card_color: null,
    omit_energy_cost: false,
    card_top_keywords: [],
    card_bottom_keywords: [],
    upgraded_content: null,
    upgraded_content_text: null,
    transformed_upgrade_cost: null,
    transformed_upgrade_star_cost: null,
    upgraded_card_top_keywords: [],
    upgraded_card_bottom_keywords: [],
    show_upgrade: false,
    token_color: null,
    token_wax: null,
    content: [
      {
        type: "text",
        text: "획득 시 및 [gold]휴식 장소[/gold]에서 최대 3번 [gold]힘[/gold]을 1 올릴 수 있습니다.",
      },
    ],
    content_text: "획득 시 및 [gold]휴식 장소[/gold]에서 최대 3번 [gold]힘[/gold]을 1 올릴 수 있습니다.",
    env: "production",
    created_at: "2026-07-26T00:00:00Z",
  },
  {
    id: "sample-cold-mittens",
    user_id: "system",
    nickname: "첨탑대장장이",
    title: "따뜻한 벙어리장갑 (냉기 버전)",
    resource_type: "relic",
    resource_id: "TOASTY_MITTENS",
    source_text: "전투 시작 시, [gold]화염 장벽[/gold]을 1장 손으로 가져옵니다.",
    source_game_locale: "kor",
    transformed_name: "시린 벙어리장갑",
    transformed_cost: null,
    transformed_star_cost: null,
    transformed_card_type: null,
    transformed_card_rarity: null,
    transformed_card_color: null,
    omit_energy_cost: false,
    card_top_keywords: [],
    card_bottom_keywords: [],
    upgraded_content: null,
    upgraded_content_text: null,
    transformed_upgrade_cost: null,
    transformed_upgrade_star_cost: null,
    upgraded_card_top_keywords: [],
    upgraded_card_bottom_keywords: [],
    show_upgrade: false,
    token_color: null,
    token_wax: null,
    content: [
      {
        type: "text",
        text: "전투 시작 시, [gold]빙하[/gold]를 1장 손으로 가져옵니다.",
      },
    ],
    content_text: "전투 시작 시, [gold]빙하[/gold]를 1장 손으로 가져옵니다.",
    env: "production",
    created_at: "2026-08-20T00:00:00Z",
  },
];
