type PatchWorkerBinding = {
  fetch(request: Request): Promise<Response>;
};

type Env = {
  PATCH_WORKER?: PatchWorkerBinding;
};

type ExecutionContextLike = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException?(): void;
};

// Generated by `opennextjs-cloudflare build`.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import openNextWorker from "../.open-next/worker.js";

function isPatchWorkerPath(pathname: string): boolean {
  return (
    pathname === "/patches" ||
    pathname.startsWith("/patches/") ||
    pathname === "/_patches" ||
    pathname.startsWith("/_patches/") ||
    /^\/[^/]+\/patches(?:\/|$)/.test(pathname)
  );
}

export default {
  fetch(request: Request, env: Env, ctx: ExecutionContextLike): Promise<Response> {
    const url = new URL(request.url);
    if (env.PATCH_WORKER && isPatchWorkerPath(url.pathname)) {
      return env.PATCH_WORKER.fetch(request);
    }
    return openNextWorker.fetch(request, env, ctx);
  },
};
